version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack-pro
    ports:
      - "4566:4566"              # LocalStack Gateway
      - "4510-4559:4510-4559"    # External services port range
      - "443:443"                # HTTPS Gateway
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-docker}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=${SERVICES:-s3,lambda,dynamodb,sqs,sns,cloudformation,cloudfront,route53,acm,iam,ssm,secretsmanager}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - DISABLE_CORS_CHECKS=${DISABLE_CORS_CHECKS:-0}
      - EXTRA_CORS_ALLOWED_ORIGINS=${EXTRA_CORS_ALLOWED_ORIGINS:-}
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL:-localhost}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
      - "./localstack-init:/etc/localstack/init"
    networks:
      - localstack-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  localstack-net:
    driver: bridge
    name: localstack-network